from . import test1
from . import test2
from . import test3
from . import test4
from . import test5
from . import test6
from . import test7
from . import test8
from . import test9
from . import test10
from . import mainTest